# This file is auto-generated by install.sh
# Run:  sudo bash install.sh
# Or copy config.py.example to config.py and fill in manually.
raise RuntimeError("config.py not configured yet — run install.sh or copy config.py.example to config.py")
